name: Auto Merge

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge changes
      run: |
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        echo $current_branch
        if [ "$current_branch" == "main" ]; then
          git checkout project1
          git merge main --no-edit

          git checkout project2
          git merge main --no-edit

          git checkout "$current_branch"
        fi
